import "./globals.css";

export const metadata = {
  title: "Web Tutorial",
  description: "Generated by feelgom",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1><a href="/">WEB</a></h1>
        <ol>
          <li><a href="/read/1">html</a></li>
          <li><a href="/read/2">css</a></li>
        </ol>
        {children}
        <ul>
          <li><a href="/Create">Create</a></li>
          <li><a href="/Update/1">Update</a></li>
          <li><input type="button" value="Delete" /></li>

        </ul>
      </body>
    </html>
  );
}
